### PR TITLE
Fix depwarn in test

### PR DESCRIPTION
**Pull request by ranjanan**
`symbol` -> `Symbol`

### CODE REVIEW

**Comment by kmsquire** [comment]
This requires Compat to work on Julia v0.4. However, I'm about to split v0.4 and v0.5 branches. Will update here when that's done.

**Comment by ranjanan** [comment]
@kmsquire are you sure? Because the `Symbol` constructor works on both v0.4 and v0.5 without the need to use `Compat`

**Comment by kmsquire** [comment]
See https://travis-ci.org/kmsquire/Logging.jl/jobs/167685951

**Comment by kmsquire** [comment]
Thanks!

**Comment by ranjanan** [comment]
@kmsquire Would you mind tagging a new release please? Thanks!

**Comment by ViralBShah** [comment]
Was a new release tagged? I got this with `Pkg.test("Mocha")`

```
WARNING: Method definition info(Any...) in module Base at util.jl:320 overwritten in module Logging at /Users/viral/.julia/v0.5/Logging/src/Logging.jl:115.
WARNING: Method definition warn(Any...) in module Base at util.jl:350 overwritten in module Logging at /Users/viral/.julia/v0.5/Logging/src/Logging.jl:115.
WARNING: Method definition warn(Any...) in module Base at util.jl:350 overwritten in module Logging at /Users/viral/.julia/v0.5/Logging/src/Logging.jl:115.
WARNING: Method definition info(Any...) in module Base at util.jl:320 overwritten in module Logging at /Users/viral/.julia/v0.5/Logging/src/Logging.jl:115
```

**Pull request merged**
